### ISSUE TITLE
can't upload

### ISSUE THREAD

**Issue by boimandude** [quaris628/EinsteinEditor#3]
when i try to upload to a saved bibite it doesn't show me any compatible files to upload to
i haven't seen any fixes of this online so I'm guessing is a bug

i made something basic to try it
clicked save to bibites
clicked templates
and got this
![image_2023-04-08_123241516](https://user-images.githubusercontent.com/130180801/230732472-d12e916a-eabd-46e7-8748-df55f7f4ade9.png)

**Comment by quaris628** [comment]
"Save to Bibite" means you're saving the brain to an existing bibite.
Bibites have more than just a brain. They have genes and other properties too.
Einstein only deals with the brain.
Create a new bibite, and save your brain to that file.
