### ISSUE TITLE
How do i save or load a bibite

### ISSUE THREAD

**Issue by StanislavMrk27** [quaris628/EinsteinEditor#4]
Whenever i try to save a bibite it says "File not found, check the file name and try again" And when i try to load a bibite it says "File format invalid"

**Comment by quaris628** [comment]
Exactly what files are you opening? They should be '.bb8's. Not templates or anything.

**Comment by StanislavMrk27** [comment]
Turns out i was loading .bb8template not .bb8. Thanks
